import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { randomUUID } from 'node:crypto';
import { DatabaseService } from '../database/database/database.service';

type Row = Record<string, any>;

@Injectable()
export class OperationsRepository {
  constructor(private readonly database: DatabaseService) {}
  get enabled() { return this.database.isConfigured(); }
  private async list(table: string, query: { search?: string; customerId?: string; siteId?: string; status?: string }) {
    const values: unknown[] = [];
    const where = ['archived_at IS NULL'];
    if (query.search) { values.push(`%${query.search.trim().toLowerCase()}%`); where.push(`(lower(name) LIKE $${values.length} OR lower(code) LIKE $${values.length})`); }
    if (query.customerId) { values.push(query.customerId); where.push(`customer_id = $${values.length}::uuid`); }
    if (query.siteId) { values.push(query.siteId); where.push(`site_id = $${values.length}::uuid`); }
    if (query.status) { values.push(query.status); where.push(`status = $${values.length}`); }
    return this.database.tenantQuery<Row>(`SELECT *, id::text AS id FROM ${table} WHERE ${where.join(' AND ')} ORDER BY created_at DESC LIMIT 200`, values);
  }
  master(entity: 'customers' | 'sites' | 'targets' | 'parts', query: any) { return this.list(`master_${entity === 'targets' ? 'service_targets' : entity}`, query); }
  async createMaster(entity: string, payload: Row) {
    const table = `master_${entity === 'targets' ? 'service_targets' : entity}`;
    const columns = Object.keys(payload).filter((key) => ['name', 'code', 'customerId', 'siteId', 'qrIdentity', 'type', 'condition', 'nextDue', 'unit', 'stock', 'compatibility', 'address', 'branch'].includes(key));
    const dbColumns = columns.map((key) => key.replace(/[A-Z]/g, (letter) => `_${letter.toLowerCase()}`));
    const values = columns.map((key) => payload[key]);
    const placeholders = values.map((_, index) => `$${index + 1}${['customerId', 'siteId'].includes(columns[index]) ? '::uuid' : ''}`);
    const result = await this.database.tenantQuery<Row>(`INSERT INTO ${table} (tenant_id, ${dbColumns.join(', ')}) VALUES (current_setting('app.tenant_id', true)::uuid, ${placeholders.join(', ')}) RETURNING *, id::text AS id`, values);
    return result[0];
  }
  async updateMaster(entity: string, id: string, payload: Row) {
    const table = `master_${entity === 'targets' ? 'service_targets' : entity}`;
    const columns = Object.keys(payload).filter((key) => ['name', 'code', 'condition', 'nextDue', 'unit', 'stock', 'compatibility', 'address', 'branch'].includes(key));
    if (!columns.length) return this.findMaster(entity, id);
    const values = columns.map((key) => payload[key]); values.push(id);
    const set = columns.map((key, index) => `${key.replace(/[A-Z]/g, (letter) => `_${letter.toLowerCase()}`)} = $${index + 1}`).join(', ');
    const result = await this.database.tenantQuery<Row>(`UPDATE ${table} SET ${set}, revision = revision + 1, updated_at = clock_timestamp() WHERE id = $${values.length}::uuid AND archived_at IS NULL RETURNING *, id::text AS id`, values);
    if (!result[0]) throw new NotFoundException('RECORD_NOT_FOUND');
    return result[0];
  }
  async findMaster(entity: string, id: string) {
    const table = `master_${entity === 'targets' ? 'service_targets' : entity}`;
    const result = await this.database.tenantQuery<Row>(`SELECT *, id::text AS id FROM ${table} WHERE id = $1::uuid AND archived_at IS NULL`, [id]);
    if (!result[0]) throw new NotFoundException('RECORD_NOT_FOUND');
    return result[0];
  }
  async resolveQr(code: string) {
    const result = await this.database.tenantQuery<Row>('SELECT t.*, t.id::text AS id, s.id::text AS "siteId", s.name AS "siteName" FROM master_service_targets t JOIN master_sites s ON s.id = t.site_id AND s.tenant_id = t.tenant_id WHERE t.qr_identity = $1 AND t.archived_at IS NULL', [code]);
    if (!result[0]) throw new NotFoundException('QR_NOT_FOUND');
    return { type: 'service_target', record: result[0] };
  }
  async importPreview(payload: { entityType: string; rows: Array<Record<string, unknown>>; duplicateMode?: string; uploadId?: string; sourceChecksum?: string }) {
    return this.database.transaction(async (client) => {
      const tenant = await client.query<{ id: string }>("SELECT current_setting('app.tenant_id', true)::uuid AS id");
      const errors: Array<{ rowNumber: number; status: string; errorCode?: string; message?: string }> = payload.rows.map((row, index) => !row.name || !row.code ? { rowNumber: index + 1, status: 'ERROR', errorCode: 'REQUIRED_FIELD', message: 'Name and code are required' } : { rowNumber: index + 1, status: 'VALID' });
      const result = await client.query<Row>('INSERT INTO import_jobs (tenant_id, entity_type, source_file_id, source_checksum, status, preview_revision, total_rows, valid_rows, error_rows, duplicate_mode) VALUES ($1::uuid, $2, $3::uuid, $4, \'PREVIEWED\', 1, $5, $6, $7, $8) RETURNING id::text AS id, entity_type AS "entityType", status, preview_revision AS "previewRevision", total_rows AS "totalRows", valid_rows AS "validRows", error_rows AS "errorRows", duplicate_mode AS "duplicateMode", created_at AS "createdAt"', [tenant.rows[0].id, payload.entityType, payload.uploadId ?? null, payload.sourceChecksum ?? null, payload.rows.length, errors.filter((row) => row.status === 'VALID').length, errors.filter((row) => row.status === 'ERROR').length, payload.duplicateMode ?? 'reject']);
      for (const row of errors) await client.query('INSERT INTO import_row_outcomes (tenant_id, import_id, row_number, status, error_code, message) VALUES ($1::uuid, $2::uuid, $3, $4, $5, $6)', [tenant.rows[0].id, result.rows[0].id, row.rowNumber, row.status, row.errorCode ?? null, row.message ?? null]);
      return { ...result.rows[0], errors: errors.filter((row) => row.status === 'ERROR') };
    });
  }
  async commitImport(importId: string, previewRevision: number) {
    return this.database.transaction(async (client) => {
      const result = await client.query<Row>("UPDATE import_jobs SET status = 'QUEUED', updated_at = clock_timestamp() WHERE id = $1::uuid AND status = 'PREVIEWED' AND preview_revision = $2 RETURNING id::text AS id, status, preview_revision AS \"previewRevision\", total_rows AS \"totalRows\", valid_rows AS \"validRows\", error_rows AS \"errorRows\"", [importId, previewRevision]);
      if (!result.rows[0]) throw new Error('IMPORT_PREVIEW_REVISION_CONFLICT');
      const tenant = await client.query<{ id: string }>("SELECT current_setting('app.tenant_id', true)::uuid AS id");
      await client.query('INSERT INTO outbox_events (id, event_id, event_type, event_version, tenant_id, payload, status) VALUES ($1::uuid, $2::uuid, $3, 1, $4::uuid, $5::jsonb, \'PENDING\')', [randomUUID(), randomUUID(), 'master.import.commit.v1', tenant.rows[0].id, JSON.stringify({ importId })]);
      return result.rows[0];
    });
  }
  async importStatus(importId: string) {
    const result = await this.database.tenantQuery<Row>('SELECT id::text AS id, entity_type AS "entityType", status, preview_revision AS "previewRevision", total_rows AS "totalRows", valid_rows AS "validRows", error_rows AS "errorRows", created_at AS "createdAt", updated_at AS "updatedAt" FROM import_jobs WHERE id = $1::uuid', [importId]);
    if (!result[0]) throw new NotFoundException('IMPORT_NOT_FOUND');
    const errors = await this.database.tenantQuery<Row>('SELECT row_number AS row, status, error_code AS code, message FROM import_row_outcomes WHERE import_id = $1::uuid AND status = \'ERROR\' ORDER BY row_number', [importId]);
    return { ...result[0], errors };
  }
  async workflows() { return this.database.tenantQuery<Row>("SELECT id::text AS id, tenant_id::text AS \"tenantId\", name, description, status, revision, schema, current_version_id::text AS \"currentVersionId\", created_at AS \"createdAt\", updated_at AS \"updatedAt\" FROM workflow_drafts WHERE archived_at IS NULL ORDER BY updated_at DESC"); }
  async workflow(id: string) { const result = await this.database.tenantQuery<Row>('SELECT id::text AS id, name, description, status, revision, schema, current_version_id::text AS "currentVersionId", created_at AS "createdAt", updated_at AS "updatedAt" FROM workflow_drafts WHERE id = $1::uuid AND archived_at IS NULL', [id]); if (!result[0]) throw new NotFoundException('WORKFLOW_NOT_FOUND'); return result[0]; }
  async createWorkflow(payload: Row) { const result = await this.database.tenantQuery<Row>('INSERT INTO workflow_drafts (tenant_id, name, description, schema) VALUES (current_setting(\'app.tenant_id\', true)::uuid, $1, $2, $3::jsonb) RETURNING id::text AS id, name, description, status, revision, schema', [payload.name, payload.description ?? '', JSON.stringify({ sections: [], fields: [], rules: [] })]); return result[0]; }
  async saveWorkflow(id: string, payload: Row, revision: number) { const result = await this.database.tenantQuery<Row>('UPDATE workflow_drafts SET name = COALESCE($1, name), description = COALESCE($2, description), schema = COALESCE($3::jsonb, schema), revision = revision + 1, updated_at = clock_timestamp() WHERE id = $4::uuid AND revision = $5 AND archived_at IS NULL RETURNING id::text AS id, name, description, status, revision, schema', [payload.name, payload.description, payload.schema ? JSON.stringify(payload.schema) : null, id, revision]); if (!result[0]) throw new Error('STALE_WORKFLOW_REVISION'); return result[0]; }
  async addToWorkflow(id: string, kind: 'sections' | 'fields' | 'rules', value: Row, revision: number) { const result = await this.database.tenantQuery<Row>(`UPDATE workflow_drafts SET schema = jsonb_set(schema, '{${kind}}', COALESCE(schema->'${kind}', '[]'::jsonb) || $1::jsonb), revision = revision + 1, updated_at = clock_timestamp() WHERE id = $2::uuid AND revision = $3 AND archived_at IS NULL RETURNING id::text AS id, name, description, status, revision, schema`, [JSON.stringify([{ id: randomUUID(), ...value }]), id, revision]); if (!result[0]) throw new Error('STALE_WORKFLOW_REVISION'); return result[0]; }
  async replaceRules(id: string, rules: unknown[], revision: number) { const result = await this.database.tenantQuery<Row>("UPDATE workflow_drafts SET schema = jsonb_set(schema, '{rules}', $1::jsonb), revision = revision + 1, updated_at = clock_timestamp() WHERE id = $2::uuid AND revision = $3 AND archived_at IS NULL RETURNING id::text AS id, name, description, status, revision, schema", [JSON.stringify(rules), id, revision]); if (!result[0]) throw new Error('STALE_WORKFLOW_REVISION'); return result[0]; }
  async publishWorkflow(id: string, revision: number, notes: string) {
    return this.database.transaction(async (client) => {
      const tenantId = await client.query<{ tenant_id: string }>("SELECT current_setting('app.tenant_id', true)::uuid AS tenant_id");
      const draft = await client.query<Row>('SELECT * FROM workflow_drafts WHERE tenant_id = $1::uuid AND id = $2::uuid AND revision = $3 FOR UPDATE', [tenantId.rows[0].tenant_id, id, revision]);
      if (!draft.rows[0]) throw new Error('STALE_WORKFLOW_REVISION');
      const snapshot = { ...draft.rows[0].schema, registryVersion: 1, notes };
      const version = await client.query<Row>('INSERT INTO workflow_versions (tenant_id, workflow_id, version, content_hash, snapshot) SELECT tenant_id, id, COALESCE((SELECT max(version) + 1 FROM workflow_versions WHERE workflow_id = $1::uuid AND tenant_id = $2::uuid), 1), encode(sha256($3::bytea), \'hex\'), $3::jsonb FROM workflow_drafts WHERE id = $1::uuid AND tenant_id = $2::uuid RETURNING id::text AS id, version, content_hash AS hash, snapshot, published_at AS "publishedAt"', [id, tenantId.rows[0].tenant_id, JSON.stringify(snapshot)]);
      await client.query("UPDATE workflow_drafts SET status = 'PUBLISHED', current_version_id = $1::uuid, revision = revision + 1, updated_at = clock_timestamp() WHERE tenant_id = $2::uuid AND id = $3::uuid", [version.rows[0].id, tenantId.rows[0].tenant_id, id]);
      await client.query('INSERT INTO outbox_events (id, event_id, event_type, event_version, tenant_id, payload, status) VALUES ($1::uuid, $2::uuid, $3, 1, $4::uuid, $5::jsonb, \'PENDING\')', [randomUUID(), randomUUID(), 'workflow.published.v1', tenantId.rows[0].tenant_id, JSON.stringify({ workflowId: id, versionId: version.rows[0].id, version: version.rows[0].version })]);
      return version.rows[0];
    });
  }
  async versions(id: string) { return this.database.tenantQuery<Row>('SELECT id::text AS id, version, content_hash AS hash, snapshot, published_at AS "publishedAt" FROM workflow_versions WHERE workflow_id = $1::uuid ORDER BY version DESC', [id]); }
  async archiveWorkflow(id: string, revision: number) { const result = await this.database.tenantQuery<Row>("UPDATE workflow_drafts SET status = 'ARCHIVED', archived_at = clock_timestamp(), revision = revision + 1 WHERE id = $1::uuid AND revision = $2 AND archived_at IS NULL RETURNING id::text AS id, status, revision", [id, revision]); if (!result[0]) throw new Error('STALE_WORKFLOW_REVISION'); return result[0]; }
  async tasks(query: any) { return this.database.tenantQuery<Row>('SELECT id::text AS id, task_number AS number, status, flags, priority, description, scheduled_at AS "scheduledAt", due_at AS "dueAt", revision, workflow_version_id::text AS "workflowVersionId", created_at AS "createdAt" FROM tasks WHERE archived_at IS NULL AND ($1 = \'\' OR lower(task_number) LIKE $2 OR lower(description) LIKE $2) AND ($3 = \'\' OR status = $3) ORDER BY scheduled_at NULLS LAST, created_at DESC LIMIT 500', [query.search ?? '', `%${(query.search ?? '').toLowerCase()}%`, query.status ?? '']); }
  async task(id: string) { const result = await this.database.tenantQuery<Row>('SELECT id::text AS id, task_number AS number, status, flags, priority, description, instructions, scheduled_at AS "scheduledAt", due_at AS "dueAt", estimated_minutes AS "estimatedMinutes", revision, workflow_version_id::text AS "workflowVersionId", customer_id::text AS "customerId", site_id::text AS "siteId", target_id::text AS "targetId" FROM tasks WHERE id = $1::uuid AND archived_at IS NULL', [id]); if (!result[0]) throw new NotFoundException('TASK_NOT_FOUND'); return result[0]; }
  async createTask(payload: Row) { return this.database.transaction(async (client) => { const tenant = await client.query<{ id: string }>("SELECT current_setting('app.tenant_id', true)::uuid AS id"); const version = await client.query<Row>('SELECT id FROM workflow_versions WHERE tenant_id = $1::uuid AND id = $2::uuid', [tenant.rows[0].id, payload.workflowVersionId]); if (!version.rows[0]) throw new Error('PUBLISHED_WORKFLOW_REQUIRED'); const number = await client.query<{ task_number: string }>("SELECT 'FBX-' || lpad(nextval('task_number_sequence')::text, 7, '0') AS task_number"); const result = await client.query<Row>('INSERT INTO tasks (tenant_id, task_number, workflow_version_id, customer_id, site_id, target_id, description, instructions, scheduled_at, due_at, estimated_minutes, priority) VALUES ($1::uuid, $2, $3::uuid, $4::uuid, $5::uuid, $6::uuid, $7, $8, $9::timestamptz, $10::timestamptz, $11, $12) RETURNING id::text AS id, task_number AS number, status, revision, workflow_version_id::text AS "workflowVersionId"', [tenant.rows[0].id, number.rows[0].task_number, payload.workflowVersionId, payload.customerId, payload.siteId, payload.targetId ?? null, payload.description ?? '', payload.instructions ?? '', payload.scheduledAt ?? null, payload.dueAt ?? null, payload.estimatedMinutes ?? null, payload.priority ?? 'NORMAL']); await client.query('INSERT INTO task_history (tenant_id, task_id, event_type, after_state) VALUES ($1::uuid, $2::uuid, $3, $4::jsonb)', [tenant.rows[0].id, result.rows[0].id, 'TASK_CREATED', JSON.stringify({ status: 'DRAFT', number: result.rows[0].number })]); await client.query('INSERT INTO outbox_events (id, event_id, event_type, event_version, tenant_id, payload, status) VALUES ($1::uuid, $2::uuid, $3, 1, $4::uuid, $5::jsonb, \'PENDING\')', [randomUUID(), randomUUID(), 'task.created.v1', tenant.rows[0].id, JSON.stringify({ taskId: result.rows[0].id, taskNumber: result.rows[0].number })]); return result.rows[0]; }); }
  async updateTask(id: string, payload: Row, revision: number) { const result = await this.database.tenantQuery<Row>('UPDATE tasks SET description = COALESCE($1, description), instructions = COALESCE($2, instructions), scheduled_at = COALESCE($3::timestamptz, scheduled_at), due_at = COALESCE($4::timestamptz, due_at), priority = COALESCE($5, priority), revision = revision + 1, updated_at = clock_timestamp() WHERE id = $6::uuid AND revision = $7 AND archived_at IS NULL RETURNING id::text AS id, task_number AS number, status, revision', [payload.description, payload.instructions, payload.scheduledAt, payload.dueAt, payload.priority, id, revision]); if (!result[0]) throw new Error('STALE_TASK_REVISION'); return result[0]; }
  async transitionTask(id: string, targetStatus: string, reason: string, revision: number) { return this.database.transaction(async (client) => { const current = await client.query<Row>('SELECT * FROM tasks WHERE id = $1::uuid AND archived_at IS NULL FOR UPDATE', [id]); if (!current.rows[0] || current.rows[0].revision !== revision) throw new Error('STALE_TASK_REVISION'); const allowed: Record<string, string[]> = { DRAFT: ['SCHEDULED', 'CANCELLED'], SCHEDULED: ['ASSIGNED', 'CANCELLED'], ASSIGNED: ['IN_PROGRESS', 'CANCELLED'], IN_PROGRESS: ['COMPLETED', 'PAUSED', 'CANCELLED'], PAUSED: ['IN_PROGRESS', 'CANCELLED'], COMPLETED: ['REOPENED'], REOPENED: ['IN_PROGRESS'] }; if (!allowed[current.rows[0].status]?.includes(targetStatus)) throw new Error('INVALID_TASK_TRANSITION'); const updated = await client.query<Row>('UPDATE tasks SET status = $1, revision = revision + 1, updated_at = clock_timestamp() WHERE id = $2::uuid RETURNING id::text AS id, task_number AS number, status, revision', [targetStatus, id]); await client.query('INSERT INTO task_history (tenant_id, task_id, event_type, before_state, after_state, reason) VALUES ((SELECT tenant_id FROM tasks WHERE id = $1::uuid), $1::uuid, $2, $3::jsonb, $4::jsonb, $5)', [id, 'TASK_TRANSITIONED', JSON.stringify({ status: current.rows[0].status }), JSON.stringify({ status: targetStatus }), reason ?? null]); await client.query('INSERT INTO outbox_events (id, event_id, event_type, event_version, tenant_id, payload, status) VALUES ($1::uuid, $2::uuid, $3, 1, (SELECT tenant_id FROM tasks WHERE id = $4::uuid), $5::jsonb, \'PENDING\')', [randomUUID(), randomUUID(), 'task.transitioned.v1', id, JSON.stringify({ taskId: id, from: current.rows[0].status, to: targetStatus })]); return updated.rows[0]; }); }
  async assignTask(id: string, payload: Row) { return this.database.transaction(async (client) => { const task = await client.query<{ tenant_id: string }>('SELECT tenant_id FROM tasks WHERE id = $1::uuid AND archived_at IS NULL FOR UPDATE', [id]); if (!task.rows[0]) throw new NotFoundException('TASK_NOT_FOUND'); if (!payload.workerId && !payload.teamId) throw new BadRequestException('ASSIGNMENT_TARGET_REQUIRED'); if (payload.workerId) { const worker = await client.query('SELECT 1 FROM users WHERE id = $1::uuid AND tenant_id = $2::uuid AND active = true', [payload.workerId, task.rows[0].tenant_id]); if (!worker.rows[0]) throw new BadRequestException('ACTIVE_WORKER_REQUIRED'); } if (payload.teamId) { const team = await client.query('SELECT 1 FROM teams WHERE id = $1::uuid AND tenant_id = $2::uuid AND active = true', [payload.teamId, task.rows[0].tenant_id]); if (!team.rows[0]) throw new BadRequestException('ACTIVE_TEAM_REQUIRED'); } if (payload.workerId && payload.teamId) { const membership = await client.query('SELECT 1 FROM team_memberships WHERE tenant_id = $1::uuid AND team_id = $2::uuid AND user_id = $3::uuid AND ends_at IS NULL', [task.rows[0].tenant_id, payload.teamId, payload.workerId]); if (!membership.rows[0]) throw new BadRequestException('WORKER_TEAM_MEMBERSHIP_REQUIRED'); } await client.query('UPDATE task_assignments SET ended_at = clock_timestamp() WHERE task_id = $1::uuid AND ended_at IS NULL', [id]); const result = await client.query<Row>('INSERT INTO task_assignments (tenant_id, task_id, worker_id, team_id, lead, reason) SELECT tenant_id, id, $2::uuid, $3::uuid, $4, $5 FROM tasks WHERE id = $1::uuid RETURNING id::text AS id, task_id::text AS "taskId", worker_id::text AS "workerId", team_id::text AS "teamId", lead, started_at AS "startedAt"', [id, payload.workerId ?? null, payload.teamId ?? null, payload.lead ?? false, payload.reason ?? null]); return result.rows[0]; }); }
  async history(id: string) { return this.database.tenantQuery<Row>('SELECT id::text AS id, event_type AS event, before_state AS "before", after_state AS "after", reason, occurred_at AS "occurredAt" FROM task_history WHERE task_id = $1::uuid ORDER BY occurred_at DESC', [id]); }
  async appendAction(id: string, event: string, payload: Row) { const result = await this.database.tenantQuery<Row>('INSERT INTO task_history (tenant_id, task_id, event_type, after_state, reason) SELECT tenant_id, id, $2, $3::jsonb, $4 FROM tasks WHERE id = $1::uuid RETURNING id::text AS id, event_type AS event, occurred_at AS "occurredAt"', [id, event, JSON.stringify(payload), payload.reason ?? null]); if (!result[0]) throw new NotFoundException('TASK_NOT_FOUND'); return result[0]; }
  async appendAttachment(id: string, payload: Row) { const result = await this.database.tenantQuery<Row>('INSERT INTO task_attachments (tenant_id, task_id, upload_id, category, created_by) SELECT tenant_id, id, $2::uuid, $3, NULLIF(current_setting(\'app.actor_id\', true), \'\')::uuid FROM tasks WHERE id = $1::uuid RETURNING id::text AS id, task_id::text AS "taskId", upload_id::text AS "uploadId", category, created_at AS "createdAt"', [id, payload.uploadId, payload.category]); if (!result[0]) throw new NotFoundException('TASK_NOT_FOUND'); return result[0]; }
}
