import { createHash } from 'node:crypto';
import { PlatformService } from './platform.service';
import { TenantContextService } from '../../tenant-context/tenant-context/tenant-context.service';

function repositoryStub() {
  return {} as ConstructorParameters<typeof PlatformService>[0];
}
function storageStub() {
  return {} as ConstructorParameters<typeof PlatformService>[2];
}
function queueStub() {
  return {} as ConstructorParameters<typeof PlatformService>[3];
}
function notificationsStub() {
  return { sendInvitation: jest.fn() } as unknown as ConstructorParameters<
    typeof PlatformService
  >[4];
}

describe('PlatformService.updateCompany — policy field validation', () => {
  let service: PlatformService;
  let token: string;

  beforeEach(() => {
    service = new PlatformService(
      repositoryStub(),
      new TenantContextService(),
      storageStub(),
      queueStub(),
      notificationsStub(),
    );
    token = 'test-session-token';
    const hash = createHash('sha256').update(token).digest('hex');
    const demoUser = service.users[0];
    service.sessions.set(hash, demoUser);
    service.sessionMetadata.set(hash, {
      familyId: 'family-1',
      tokenType: 'access',
      expiresAt: Date.now() + 60_000,
      revoked: false,
    });
  });

  it('accepts a fully valid extended policy patch', async () => {
    const result = await service.updateCompany(token, {
      contactFooter: 'Call us at +968 2400 0000',
      reportFooter: 'Generated by FieldBrix',
      gpsRadiusMeters: 150,
      signaturePolicy: { required: true },
      refusalPolicy: { allowed: true, requireReason: true },
      unavailablePolicy: { allowed: true, requireReason: false },
      approvalPolicy: { required: true, approverRoleKey: 'role-supervisor' },
      latePolicy: { graceMinutes: 15 },
      exceptionPolicy: { requireReason: true },
    });
    expect(result.gpsRadiusMeters).toBe(150);
    expect(result.latePolicy).toEqual({ graceMinutes: 15 });
  });

  it('rejects a GPS radius outside the allowed bounds', async () => {
    await expect(
      service.updateCompany(token, { gpsRadiusMeters: 1 }),
    ).rejects.toThrow('INVALID_GPS_RADIUS');
    await expect(
      service.updateCompany(token, { gpsRadiusMeters: 5000 }),
    ).rejects.toThrow('INVALID_GPS_RADIUS');
  });

  it('rejects a policy object missing its required key', async () => {
    await expect(
      service.updateCompany(token, { refusalPolicy: { allowed: true } }),
    ).rejects.toThrow('INVALID_REFUSAL_POLICY');
  });

  it('rejects a non-integer grace period on the late policy', async () => {
    await expect(
      service.updateCompany(token, {
        latePolicy: { graceMinutes: 'soon' as unknown as number },
      }),
    ).rejects.toThrow('INVALID_LATE_POLICY');
  });

  it('still rejects branch-scoped terminology keys', async () => {
    await expect(
      service.updateCompany(token, {
        terminology: { 'branch.muscat.task': 'Job' },
      }),
    ).rejects.toThrow('BRANCH_TERMINOLOGY_NOT_ALLOWED');
  });
});
