CREATE EXTENSION IF NOT EXISTS citext;
CREATE TABLE IF NOT EXISTS tenants (id UUID PRIMARY KEY, name TEXT NOT NULL, status TEXT NOT NULL CHECK (status IN ('ACTIVE','SUSPENDED','ARCHIVED')), timezone TEXT NOT NULL DEFAULT 'UTC', settings JSONB NOT NULL DEFAULT '{}', revision BIGINT NOT NULL DEFAULT 1, created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(), updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp());
CREATE TABLE IF NOT EXISTS users (id UUID PRIMARY KEY, tenant_id UUID NOT NULL REFERENCES tenants(id), email CITEXT NOT NULL, display_name TEXT NOT NULL, password_hash TEXT NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(), UNIQUE (tenant_id, email));
CREATE TABLE IF NOT EXISTS roles (id UUID PRIMARY KEY, tenant_id UUID NOT NULL REFERENCES tenants(id), name TEXT NOT NULL, preset_source TEXT, immutable BOOLEAN NOT NULL DEFAULT FALSE, revision BIGINT NOT NULL DEFAULT 1, UNIQUE (tenant_id, name));
CREATE TABLE IF NOT EXISTS permissions (key TEXT PRIMARY KEY, module TEXT NOT NULL, resource TEXT NOT NULL, action TEXT NOT NULL, scope TEXT[] NOT NULL DEFAULT '{}');
CREATE TABLE IF NOT EXISTS role_permissions (role_id UUID NOT NULL REFERENCES roles(id), permission_key TEXT NOT NULL REFERENCES permissions(key), PRIMARY KEY (role_id, permission_key));
CREATE TABLE IF NOT EXISTS tenant_user_roles (tenant_id UUID NOT NULL REFERENCES tenants(id), user_id UUID NOT NULL REFERENCES users(id), role_id UUID NOT NULL REFERENCES roles(id), created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(), PRIMARY KEY (tenant_id, user_id, role_id));
CREATE TABLE IF NOT EXISTS sessions (id UUID PRIMARY KEY, user_id UUID NOT NULL REFERENCES users(id), tenant_id UUID NOT NULL REFERENCES tenants(id), token_hash TEXT NOT NULL UNIQUE, expires_at TIMESTAMPTZ NOT NULL, revoked_at TIMESTAMPTZ, family_id UUID NOT NULL);
CREATE TABLE IF NOT EXISTS idempotency_records (tenant_id UUID, key UUID NOT NULL, request_hash TEXT NOT NULL, status_code INTEGER NOT NULL, response JSONB NOT NULL, expires_at TIMESTAMPTZ NOT NULL, PRIMARY KEY (tenant_id, key));
CREATE TABLE IF NOT EXISTS audit_logs (id UUID PRIMARY KEY, tenant_id UUID, actor_id UUID, action TEXT NOT NULL, target_type TEXT NOT NULL, target_id TEXT, payload JSONB NOT NULL DEFAULT '{}', previous_hash TEXT, hash TEXT NOT NULL, occurred_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp());
CREATE TABLE IF NOT EXISTS branches (id UUID PRIMARY KEY, tenant_id UUID NOT NULL REFERENCES tenants(id), name TEXT NOT NULL, timezone TEXT NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE, UNIQUE (tenant_id, name));
CREATE TABLE IF NOT EXISTS teams (id UUID PRIMARY KEY, tenant_id UUID NOT NULL REFERENCES tenants(id), name TEXT NOT NULL, lead_user_id UUID, active BOOLEAN NOT NULL DEFAULT TRUE, UNIQUE (tenant_id, name));
CREATE TABLE IF NOT EXISTS invitations (id UUID PRIMARY KEY, tenant_id UUID NOT NULL REFERENCES tenants(id), email CITEXT NOT NULL, token_hash TEXT NOT NULL UNIQUE, expires_at TIMESTAMPTZ NOT NULL, accepted_at TIMESTAMPTZ);
CREATE INDEX IF NOT EXISTS audit_logs_tenant_time_idx ON audit_logs (tenant_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS sessions_user_active_idx ON sessions (user_id, revoked_at, expires_at);
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS users_tenant_isolation ON users;
DROP POLICY IF EXISTS roles_tenant_isolation ON roles;
DROP POLICY IF EXISTS audit_tenant_isolation ON audit_logs;
CREATE POLICY users_tenant_isolation ON users USING (tenant_id::text = current_setting('app.tenant_id', true));
CREATE POLICY roles_tenant_isolation ON roles USING (tenant_id::text = current_setting('app.tenant_id', true));
CREATE POLICY audit_tenant_isolation ON audit_logs USING (tenant_id IS NULL OR tenant_id::text = current_setting('app.tenant_id', true));
