-- Configurable Field Service Platform
-- PostgreSQL 16+ production-oriented baseline schema
-- Assumptions: UUIDv7 values are generated by the application; UTC timestamptz;
-- tenant context is set per transaction with SET LOCAL app.tenant_id = '<uuid>'.

BEGIN;

CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS btree_gin;

CREATE SCHEMA IF NOT EXISTS field_ops;
SET search_path = field_ops, public;

CREATE TYPE user_status AS ENUM ('active', 'disabled');
CREATE TYPE tenant_status AS ENUM ('trial', 'active', 'suspended', 'closed');
CREATE TYPE membership_role AS ENUM ('company_admin', 'supervisor', 'field_worker');
CREATE TYPE membership_status AS ENUM ('invited', 'active', 'disabled');
CREATE TYPE workflow_status AS ENUM ('active', 'archived');
CREATE TYPE workflow_version_status AS ENUM ('draft', 'published', 'archived');
CREATE TYPE field_type AS ENUM (
  'section', 'instruction', 'text', 'large_text', 'number', 'boolean',
  'single_choice', 'multiple_choice', 'date', 'time', 'datetime', 'gps',
  'image', 'file', 'scanner', 'lookup', 'signature', 'otp',
  'repeatable_group', 'calculated'
);
CREATE TYPE rule_conjunction AS ENUM ('and', 'or');
CREATE TYPE rule_operator AS ENUM (
  'equals', 'not_equals', 'contains', 'not_contains', 'is_empty', 'is_not_empty',
  'matches_format', 'greater_than', 'greater_or_equal', 'less_than',
  'less_or_equal', 'between', 'outside_range', 'is_selected', 'is_not_selected',
  'contains_option', 'contains_all_options', 'before', 'after', 'inside_radius',
  'outside_radius', 'accuracy_below', 'count_below', 'count_at_or_above',
  'matches_task_target', 'does_not_match_task_target', 'record_found', 'record_not_found'
);
CREATE TYPE rule_action_type AS ENUM (
  'show', 'hide', 'require', 'make_optional', 'enable', 'disable', 'set_value',
  'show_message', 'require_note', 'require_photo', 'require_signature',
  'require_supervisor_review', 'skip_section', 'set_result', 'block_submission',
  'recommend_follow_up', 'raise_exception'
);
CREATE TYPE recurrence_status AS ENUM ('draft', 'active', 'paused', 'ended');
CREATE TYPE task_priority AS ENUM ('low', 'normal', 'high', 'urgent');
CREATE TYPE task_status AS ENUM (
  'draft', 'assigned', 'accepted', 'in_progress', 'paused', 'submitted',
  'rejected', 'completed', 'cancelled'
);
CREATE TYPE task_result AS ENUM ('passed', 'partial', 'failed', 'safety_stop', 'follow_up_required');
CREATE TYPE task_link_type AS ENUM ('follow_up', 'rework', 'duplicate', 'related');
CREATE TYPE task_run_state AS ENUM ('draft', 'submitted', 'rejected', 'approved');
CREATE TYPE answer_validation_status AS ENUM ('unvalidated', 'valid', 'warning', 'invalid');
CREATE TYPE section_result AS ENUM ('pass', 'warning', 'partial', 'fail', 'blocked', 'not_applicable');
CREATE TYPE evidence_type AS ENUM ('image', 'file', 'signature');
CREATE TYPE capture_source AS ENUM ('camera', 'gallery', 'file_picker', 'generated');
CREATE TYPE upload_status AS ENUM ('pending', 'uploading', 'uploaded', 'failed');
CREATE TYPE gps_event_type AS ENUM ('duty_start', 'duty_end', 'check_in', 'check_out', 'evidence_capture');
CREATE TYPE confirmation_method AS ENUM ('signature', 'otp', 'none');
CREATE TYPE confirmation_status AS ENUM ('confirmed', 'customer_unavailable', 'customer_refused', 'not_required');
CREATE TYPE exception_type AS ENUM (
  'safety', 'gps', 'target_mismatch', 'validation', 'final_test',
  'customer_confirmation', 'sync', 'other'
);
CREATE TYPE exception_severity AS ENUM ('info', 'warning', 'critical');
CREATE TYPE exception_status AS ENUM ('open', 'accepted', 'resolved', 'dismissed');
CREATE TYPE review_decision AS ENUM ('approved', 'rejected', 'follow_up_required');
CREATE TYPE request_status AS ENUM ('pending', 'approved', 'rejected');
CREATE TYPE device_status AS ENUM ('active', 'revoked');
CREATE TYPE sync_mutation_status AS ENUM ('received', 'applied', 'rejected', 'duplicate');
CREATE TYPE import_type AS ENUM ('users', 'customers', 'sites', 'service_targets', 'parts', 'tasks');
CREATE TYPE import_status AS ENUM ('uploaded', 'validating', 'ready', 'processing', 'completed', 'failed');
CREATE TYPE import_row_status AS ENUM ('valid', 'warning', 'rejected', 'created', 'updated');
CREATE TYPE notification_status AS ENUM ('unread', 'read', 'dismissed');

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := clock_timestamp();
  RETURN NEW;
END;
$$;

CREATE TABLE users (
  id uuid PRIMARY KEY,
  auth_subject text NOT NULL UNIQUE,
  email citext,
  phone_e164 text,
  display_name text NOT NULL,
  status user_status NOT NULL DEFAULT 'active',
  last_login_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  CONSTRAINT users_contact_ck CHECK (email IS NOT NULL OR phone_e164 IS NOT NULL)
);
CREATE UNIQUE INDEX users_email_uq ON users (email) WHERE email IS NOT NULL;
CREATE UNIQUE INDEX users_phone_uq ON users (phone_e164) WHERE phone_e164 IS NOT NULL;

CREATE TABLE platform_admins (
  user_id uuid PRIMARY KEY REFERENCES users(id) ON DELETE RESTRICT,
  role text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE tenants (
  id uuid PRIMARY KEY,
  slug citext NOT NULL UNIQUE,
  legal_name text NOT NULL,
  display_name text NOT NULL,
  status tenant_status NOT NULL DEFAULT 'trial',
  default_timezone text NOT NULL DEFAULT 'UTC',
  default_locale text NOT NULL DEFAULT 'en',
  plan_code text,
  user_limit integer CHECK (user_limit IS NULL OR user_limit > 0),
  monthly_task_limit bigint CHECK (monthly_task_limit IS NULL OR monthly_task_limit > 0),
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp()
);
CREATE INDEX tenants_status_ix ON tenants (status);

CREATE TABLE tenant_settings (
  tenant_id uuid PRIMARY KEY REFERENCES tenants(id) ON DELETE CASCADE,
  terminology jsonb NOT NULL DEFAULT '{}'::jsonb,
  task_policy jsonb NOT NULL DEFAULT '{}'::jsonb,
  evidence_policy jsonb NOT NULL DEFAULT '{}'::jsonb,
  report_branding jsonb NOT NULL DEFAULT '{}'::jsonb,
  feature_flags jsonb NOT NULL DEFAULT '{}'::jsonb,
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE branches (
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  id uuid NOT NULL,
  code citext NOT NULL,
  name text NOT NULL,
  timezone text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY (tenant_id, id),
  UNIQUE (tenant_id, code)
);
CREATE INDEX branches_active_name_ix ON branches (tenant_id, is_active, name);

CREATE TABLE tenant_users (
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  id uuid NOT NULL,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  branch_id uuid,
  supervisor_tenant_user_id uuid,
  role membership_role NOT NULL,
  status membership_status NOT NULL DEFAULT 'invited',
  employee_code citext,
  permission_overrides jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY (tenant_id, id),
  UNIQUE (tenant_id, user_id),
  FOREIGN KEY (tenant_id, branch_id) REFERENCES branches(tenant_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (tenant_id, supervisor_tenant_user_id)
    REFERENCES tenant_users(tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT tenant_users_not_own_supervisor_ck CHECK (id <> supervisor_tenant_user_id)
);
CREATE UNIQUE INDEX tenant_users_employee_code_uq
  ON tenant_users (tenant_id, employee_code) WHERE employee_code IS NOT NULL;
CREATE INDEX tenant_users_role_status_ix ON tenant_users (tenant_id, role, status);
CREATE INDEX tenant_users_branch_status_ix ON tenant_users (tenant_id, branch_id, status);
CREATE INDEX tenant_users_supervisor_status_ix ON tenant_users (tenant_id, supervisor_tenant_user_id, status);

CREATE TABLE teams (
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  id uuid NOT NULL,
  branch_id uuid,
  code citext NOT NULL,
  name text NOT NULL,
  supervisor_tenant_user_id uuid,
  skills jsonb NOT NULL DEFAULT '[]'::jsonb,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY (tenant_id, id),
  UNIQUE (tenant_id, code),
  FOREIGN KEY (tenant_id, branch_id) REFERENCES branches(tenant_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (tenant_id, supervisor_tenant_user_id)
    REFERENCES tenant_users(tenant_id, id) ON DELETE RESTRICT
);
CREATE INDEX teams_branch_active_ix ON teams (tenant_id, branch_id, is_active);
CREATE INDEX teams_supervisor_active_ix ON teams (tenant_id, supervisor_tenant_user_id, is_active);

CREATE TABLE team_members (
  tenant_id uuid NOT NULL,
  team_id uuid NOT NULL,
  tenant_user_id uuid NOT NULL,
  is_lead boolean NOT NULL DEFAULT false,
  joined_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  left_at timestamptz,
  PRIMARY KEY (tenant_id, team_id, tenant_user_id),
  FOREIGN KEY (tenant_id, team_id) REFERENCES teams(tenant_id, id) ON DELETE CASCADE,
  FOREIGN KEY (tenant_id, tenant_user_id) REFERENCES tenant_users(tenant_id, id) ON DELETE CASCADE,
  CONSTRAINT team_members_dates_ck CHECK (left_at IS NULL OR left_at >= joined_at)
);
CREATE INDEX team_members_user_active_ix
  ON team_members (tenant_id, tenant_user_id) WHERE left_at IS NULL;
CREATE UNIQUE INDEX team_members_one_active_lead_uq
  ON team_members (tenant_id, team_id) WHERE is_lead AND left_at IS NULL;

CREATE TABLE customers (
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  id uuid NOT NULL,
  customer_code citext NOT NULL,
  name text NOT NULL,
  customer_type text,
  contact_name text,
  phone_e164 text,
  email citext,
  billing_address text,
  notes text,
  is_active boolean NOT NULL DEFAULT true,
  deleted_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY (tenant_id, id),
  UNIQUE (tenant_id, customer_code)
);
CREATE INDEX customers_active_name_ix ON customers (tenant_id, is_active, name);
CREATE INDEX customers_name_trgm_ix ON customers USING gin (tenant_id, name gin_trgm_ops);

CREATE TABLE sites (
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  id uuid NOT NULL,
  customer_id uuid NOT NULL,
  site_code citext NOT NULL,
  name text NOT NULL,
  address_line text,
  city text,
  region text,
  postal_code text,
  latitude numeric(9,6),
  longitude numeric(9,6),
  geofence_radius_m integer CHECK (geofence_radius_m IS NULL OR geofence_radius_m BETWEEN 10 AND 50000),
  contact_name text,
  contact_phone_e164 text,
  access_instructions text,
  safety_instructions text,
  working_hours jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_active boolean NOT NULL DEFAULT true,
  deleted_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY (tenant_id, id),
  UNIQUE (tenant_id, site_code),
  UNIQUE (tenant_id, id, customer_id),
  FOREIGN KEY (tenant_id, customer_id) REFERENCES customers(tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT sites_latitude_ck CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),
  CONSTRAINT sites_longitude_ck CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180),
  CONSTRAINT sites_coordinates_pair_ck CHECK ((latitude IS NULL) = (longitude IS NULL))
);
CREATE INDEX sites_customer_active_ix ON sites (tenant_id, customer_id, is_active);
CREATE INDEX sites_active_name_ix ON sites (tenant_id, is_active, name);

CREATE TABLE service_targets (
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  id uuid NOT NULL,
  site_id uuid NOT NULL,
  target_code citext,
  qr_barcode text,
  category text NOT NULL,
  name text NOT NULL,
  brand text,
  model text,
  serial_number text,
  capacity_value numeric,
  capacity_unit text,
  installed_at date,
  warranty_expires_at date,
  floor_room_zone text,
  condition_status text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_active boolean NOT NULL DEFAULT true,
  deleted_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY (tenant_id, id),
  UNIQUE (tenant_id, id, site_id),
  FOREIGN KEY (tenant_id, site_id) REFERENCES sites(tenant_id, id) ON DELETE RESTRICT
);
CREATE UNIQUE INDEX service_targets_code_uq
  ON service_targets (tenant_id, target_code) WHERE target_code IS NOT NULL;
CREATE UNIQUE INDEX service_targets_barcode_uq
  ON service_targets (tenant_id, qr_barcode) WHERE qr_barcode IS NOT NULL;
CREATE INDEX service_targets_site_active_ix ON service_targets (tenant_id, site_id, is_active);
CREATE INDEX service_targets_category_active_ix ON service_targets (tenant_id, category, is_active);
CREATE INDEX service_targets_serial_ix
  ON service_targets (tenant_id, serial_number) WHERE serial_number IS NOT NULL;

CREATE TABLE parts (
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  id uuid NOT NULL,
  part_code citext NOT NULL,
  name text NOT NULL,
  category text,
  unit text,
  compatibility jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY (tenant_id, id),
  UNIQUE (tenant_id, part_code)
);
CREATE INDEX parts_category_active_ix ON parts (tenant_id, category, is_active);
CREATE INDEX parts_name_trgm_ix ON parts USING gin (tenant_id, name gin_trgm_ops);

CREATE TABLE workflows (
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  id uuid NOT NULL,
  code citext NOT NULL,
  name text NOT NULL,
  description text,
  industry_category text,
  work_type text,
  target_required boolean NOT NULL DEFAULT false,
  status workflow_status NOT NULL DEFAULT 'active',
  current_published_version_id uuid,
  created_by_tenant_user_id uuid NOT NULL,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY (tenant_id, id),
  UNIQUE (tenant_id, code),
  FOREIGN KEY (tenant_id, created_by_tenant_user_id)
    REFERENCES tenant_users(tenant_id, id) ON DELETE RESTRICT
);
CREATE INDEX workflows_status_name_ix ON workflows (tenant_id, status, name);

CREATE TABLE workflow_versions (
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  id uuid NOT NULL,
  workflow_id uuid NOT NULL,
  version_no integer NOT NULL CHECK (version_no > 0),
  status workflow_version_status NOT NULL DEFAULT 'draft',
  configuration jsonb NOT NULL DEFAULT '{}'::jsonb,
  change_summary text,
  created_by_tenant_user_id uuid NOT NULL,
  published_by_tenant_user_id uuid,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  published_at timestamptz,
  archived_at timestamptz,
  PRIMARY KEY (tenant_id, id),
  UNIQUE (tenant_id, workflow_id, version_no),
  UNIQUE (tenant_id, id, workflow_id),
  FOREIGN KEY (tenant_id, workflow_id) REFERENCES workflows(tenant_id, id) ON DELETE CASCADE,
  FOREIGN KEY (tenant_id, created_by_tenant_user_id)
    REFERENCES tenant_users(tenant_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (tenant_id, published_by_tenant_user_id)
    REFERENCES tenant_users(tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT workflow_versions_publish_ck CHECK (
    (status = 'published' AND published_at IS NOT NULL AND published_by_tenant_user_id IS NOT NULL)
    OR status <> 'published'
  )
);
CREATE UNIQUE INDEX workflow_versions_one_published_uq
  ON workflow_versions (tenant_id, workflow_id) WHERE status = 'published';

ALTER TABLE workflows
  ADD CONSTRAINT workflows_published_version_fk
  FOREIGN KEY (tenant_id, current_published_version_id, id)
  REFERENCES workflow_versions(tenant_id, id, workflow_id) ON DELETE RESTRICT;

CREATE TABLE workflow_sections (
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  id uuid NOT NULL,
  workflow_version_id uuid NOT NULL,
  section_key text NOT NULL,
  title text NOT NULL,
  description text,
  position integer NOT NULL CHECK (position >= 0),
  is_repeatable boolean NOT NULL DEFAULT false,
  settings jsonb NOT NULL DEFAULT '{}'::jsonb,
  PRIMARY KEY (tenant_id, id),
  UNIQUE (tenant_id, workflow_version_id, section_key),
  UNIQUE (tenant_id, workflow_version_id, position),
  UNIQUE (tenant_id, id, workflow_version_id),
  FOREIGN KEY (tenant_id, workflow_version_id)
    REFERENCES workflow_versions(tenant_id, id) ON DELETE CASCADE
);

CREATE TABLE workflow_fields (
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  id uuid NOT NULL,
  workflow_version_id uuid NOT NULL,
  section_id uuid NOT NULL,
  parent_group_field_id uuid,
  field_key text NOT NULL,
  field_type field_type NOT NULL,
  label text NOT NULL,
  description text,
  placeholder text,
  position integer NOT NULL CHECK (position >= 0),
  required_by_default boolean NOT NULL DEFAULT false,
  read_only boolean NOT NULL DEFAULT false,
  default_value jsonb,
  validation jsonb NOT NULL DEFAULT '{}'::jsonb,
  evidence_policy jsonb NOT NULL DEFAULT '{}'::jsonb,
  report_policy jsonb NOT NULL DEFAULT '{}'::jsonb,
  privacy_policy jsonb NOT NULL DEFAULT '{}'::jsonb,
  PRIMARY KEY (tenant_id, id),
  UNIQUE (tenant_id, workflow_version_id, field_key),
  UNIQUE (tenant_id, section_id, position),
  UNIQUE (tenant_id, id, workflow_version_id),
  FOREIGN KEY (tenant_id, workflow_version_id)
    REFERENCES workflow_versions(tenant_id, id) ON DELETE CASCADE,
  FOREIGN KEY (tenant_id, section_id, workflow_version_id)
    REFERENCES workflow_sections(tenant_id, id, workflow_version_id) ON DELETE CASCADE,
  FOREIGN KEY (tenant_id, parent_group_field_id, workflow_version_id)
    REFERENCES workflow_fields(tenant_id, id, workflow_version_id) ON DELETE CASCADE
);
CREATE INDEX workflow_fields_parent_ix ON workflow_fields (tenant_id, parent_group_field_id, position);

CREATE TABLE workflow_field_options (
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  id uuid NOT NULL,
  field_id uuid NOT NULL,
  option_key text NOT NULL,
  label text NOT NULL,
  position integer NOT NULL CHECK (position >= 0),
  is_active boolean NOT NULL DEFAULT true,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  PRIMARY KEY (tenant_id, id),
  UNIQUE (tenant_id, field_id, option_key),
  UNIQUE (tenant_id, field_id, position),
  FOREIGN KEY (tenant_id, field_id) REFERENCES workflow_fields(tenant_id, id) ON DELETE CASCADE
);

CREATE TABLE workflow_rules (
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  id uuid NOT NULL,
  workflow_version_id uuid NOT NULL,
  name text NOT NULL,
  priority integer NOT NULL DEFAULT 100,
  is_active boolean NOT NULL DEFAULT true,
  stop_processing boolean NOT NULL DEFAULT false,
  PRIMARY KEY (tenant_id, id),
  UNIQUE (tenant_id, workflow_version_id, name),
  FOREIGN KEY (tenant_id, workflow_version_id)
    REFERENCES workflow_versions(tenant_id, id) ON DELETE CASCADE
);
CREATE INDEX workflow_rules_priority_ix ON workflow_rules (tenant_id, workflow_version_id, priority);

CREATE TABLE workflow_rule_conditions (
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  id uuid NOT NULL,
  rule_id uuid NOT NULL,
  source_field_id uuid,
  group_no integer NOT NULL DEFAULT 0 CHECK (group_no >= 0),
  position integer NOT NULL CHECK (position >= 0),
  conjunction rule_conjunction NOT NULL DEFAULT 'and',
  operator rule_operator NOT NULL,
  comparison_value jsonb,
  PRIMARY KEY (tenant_id, id),
  UNIQUE (tenant_id, rule_id, group_no, position),
  FOREIGN KEY (tenant_id, rule_id) REFERENCES workflow_rules(tenant_id, id) ON DELETE CASCADE,
  FOREIGN KEY (tenant_id, source_field_id) REFERENCES workflow_fields(tenant_id, id) ON DELETE CASCADE
);
CREATE INDEX workflow_rule_conditions_field_ix ON workflow_rule_conditions (tenant_id, source_field_id);

CREATE TABLE workflow_rule_actions (
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  id uuid NOT NULL,
  rule_id uuid NOT NULL,
  target_field_id uuid,
  target_section_id uuid,
  position integer NOT NULL CHECK (position >= 0),
  action_type rule_action_type NOT NULL,
  action_value jsonb,
  PRIMARY KEY (tenant_id, id),
  UNIQUE (tenant_id, rule_id, position),
  FOREIGN KEY (tenant_id, rule_id) REFERENCES workflow_rules(tenant_id, id) ON DELETE CASCADE,
  FOREIGN KEY (tenant_id, target_field_id) REFERENCES workflow_fields(tenant_id, id) ON DELETE CASCADE,
  FOREIGN KEY (tenant_id, target_section_id) REFERENCES workflow_sections(tenant_id, id) ON DELETE CASCADE,
  CONSTRAINT workflow_rule_actions_target_ck CHECK (
    num_nonnulls(target_field_id, target_section_id) <= 1
  )
);
CREATE INDEX workflow_rule_actions_field_ix ON workflow_rule_actions (tenant_id, target_field_id);
CREATE INDEX workflow_rule_actions_section_ix ON workflow_rule_actions (tenant_id, target_section_id);

CREATE TABLE recurrence_plans (
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  id uuid NOT NULL,
  plan_code citext NOT NULL,
  customer_id uuid NOT NULL,
  site_id uuid NOT NULL,
  service_target_id uuid,
  workflow_id uuid NOT NULL,
  assigned_tenant_user_id uuid,
  assigned_team_id uuid,
  responsible_lead_id uuid,
  schedule_rule jsonb NOT NULL,
  timezone text NOT NULL,
  starts_on date NOT NULL,
  ends_on date,
  generate_days_ahead integer NOT NULL DEFAULT 7 CHECK (generate_days_ahead BETWEEN 0 AND 365),
  default_priority task_priority NOT NULL DEFAULT 'normal',
  instructions text,
  next_generation_at timestamptz,
  status recurrence_status NOT NULL DEFAULT 'draft',
  created_by_tenant_user_id uuid NOT NULL,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY (tenant_id, id),
  UNIQUE (tenant_id, plan_code),
  FOREIGN KEY (tenant_id, customer_id) REFERENCES customers(tenant_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (tenant_id, site_id, customer_id)
    REFERENCES sites(tenant_id, id, customer_id) ON DELETE RESTRICT,
  FOREIGN KEY (tenant_id, service_target_id, site_id)
    REFERENCES service_targets(tenant_id, id, site_id) ON DELETE RESTRICT,
  FOREIGN KEY (tenant_id, workflow_id) REFERENCES workflows(tenant_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (tenant_id, assigned_tenant_user_id) REFERENCES tenant_users(tenant_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (tenant_id, assigned_team_id) REFERENCES teams(tenant_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (tenant_id, responsible_lead_id) REFERENCES tenant_users(tenant_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (tenant_id, created_by_tenant_user_id) REFERENCES tenant_users(tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT recurrence_plans_dates_ck CHECK (ends_on IS NULL OR ends_on >= starts_on),
  CONSTRAINT recurrence_plans_assignment_ck CHECK (
    num_nonnulls(assigned_tenant_user_id, assigned_team_id) <= 1
  )
);
CREATE INDEX recurrence_plans_generation_ix ON recurrence_plans (tenant_id, status, next_generation_at);
CREATE INDEX recurrence_plans_site_status_ix ON recurrence_plans (tenant_id, site_id, status);

CREATE TABLE tasks (
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  id uuid NOT NULL,
  task_no citext NOT NULL,
  external_ref text,
  recurrence_plan_id uuid,
  customer_id uuid NOT NULL,
  site_id uuid NOT NULL,
  service_target_id uuid,
  workflow_version_id uuid NOT NULL,
  work_type text NOT NULL,
  title text,
  description text,
  instructions text,
  priority task_priority NOT NULL DEFAULT 'normal',
  status task_status NOT NULL DEFAULT 'draft',
  result task_result,
  scheduled_start timestamptz,
  scheduled_end timestamptz,
  due_at timestamptz,
  started_at timestamptz,
  submitted_at timestamptz,
  completed_at timestamptz,
  cancelled_at timestamptz,
  cancellation_reason text,
  created_by_tenant_user_id uuid NOT NULL,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY (tenant_id, id),
  UNIQUE (tenant_id, task_no),
  UNIQUE (tenant_id, id, workflow_version_id),
  FOREIGN KEY (tenant_id, recurrence_plan_id) REFERENCES recurrence_plans(tenant_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (tenant_id, customer_id) REFERENCES customers(tenant_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (tenant_id, site_id, customer_id)
    REFERENCES sites(tenant_id, id, customer_id) ON DELETE RESTRICT,
  FOREIGN KEY (tenant_id, service_target_id, site_id)
    REFERENCES service_targets(tenant_id, id, site_id) ON DELETE RESTRICT,
  FOREIGN KEY (tenant_id, workflow_version_id) REFERENCES workflow_versions(tenant_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (tenant_id, created_by_tenant_user_id) REFERENCES tenant_users(tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT tasks_schedule_ck CHECK (
    scheduled_end IS NULL OR scheduled_start IS NULL OR scheduled_end >= scheduled_start
  ),
  CONSTRAINT tasks_cancellation_ck CHECK (
    (status = 'cancelled' AND cancelled_at IS NOT NULL AND cancellation_reason IS NOT NULL)
    OR status <> 'cancelled'
  )
);
CREATE UNIQUE INDEX tasks_external_ref_uq ON tasks (tenant_id, external_ref) WHERE external_ref IS NOT NULL;
CREATE INDEX tasks_status_schedule_ix ON tasks (tenant_id, status, scheduled_start);
CREATE INDEX tasks_status_due_ix ON tasks (tenant_id, status, due_at);
CREATE INDEX tasks_customer_history_ix ON tasks (tenant_id, customer_id, created_at DESC);
CREATE INDEX tasks_site_history_ix ON tasks (tenant_id, site_id, created_at DESC);
CREATE INDEX tasks_target_history_ix ON tasks (tenant_id, service_target_id, created_at DESC);
CREATE INDEX tasks_recurrence_schedule_ix ON tasks (tenant_id, recurrence_plan_id, scheduled_start);
CREATE INDEX tasks_active_due_px ON tasks (tenant_id, due_at)
  WHERE status IN ('assigned', 'accepted', 'in_progress', 'paused', 'rejected');

CREATE TABLE task_assignments (
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  id uuid NOT NULL,
  task_id uuid NOT NULL,
  tenant_user_id uuid,
  team_id uuid,
  responsible_lead_id uuid,
  is_primary boolean NOT NULL DEFAULT true,
  assigned_by_tenant_user_id uuid NOT NULL,
  assigned_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  accepted_at timestamptz,
  ended_at timestamptz,
  end_reason text,
  PRIMARY KEY (tenant_id, id),
  FOREIGN KEY (tenant_id, task_id) REFERENCES tasks(tenant_id, id) ON DELETE CASCADE,
  FOREIGN KEY (tenant_id, tenant_user_id) REFERENCES tenant_users(tenant_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (tenant_id, team_id) REFERENCES teams(tenant_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (tenant_id, responsible_lead_id) REFERENCES tenant_users(tenant_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (tenant_id, assigned_by_tenant_user_id) REFERENCES tenant_users(tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT task_assignments_assignee_ck CHECK (num_nonnulls(tenant_user_id, team_id) = 1),
  CONSTRAINT task_assignments_team_lead_ck CHECK (team_id IS NOT NULL OR responsible_lead_id IS NULL),
  CONSTRAINT task_assignments_dates_ck CHECK (ended_at IS NULL OR ended_at >= assigned_at)
);
CREATE UNIQUE INDEX task_assignments_active_primary_uq
  ON task_assignments (tenant_id, task_id) WHERE is_primary AND ended_at IS NULL;
CREATE INDEX task_assignments_user_active_ix
  ON task_assignments (tenant_id, tenant_user_id, assigned_at DESC) WHERE ended_at IS NULL;
CREATE INDEX task_assignments_team_active_ix
  ON task_assignments (tenant_id, team_id, assigned_at DESC) WHERE ended_at IS NULL;

CREATE TABLE task_links (
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  source_task_id uuid NOT NULL,
  target_task_id uuid NOT NULL,
  link_type task_link_type NOT NULL,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY (tenant_id, source_task_id, target_task_id, link_type),
  FOREIGN KEY (tenant_id, source_task_id) REFERENCES tasks(tenant_id, id) ON DELETE CASCADE,
  FOREIGN KEY (tenant_id, target_task_id) REFERENCES tasks(tenant_id, id) ON DELETE CASCADE,
  CONSTRAINT task_links_not_self_ck CHECK (source_task_id <> target_task_id)
);
CREATE INDEX task_links_target_ix ON task_links (tenant_id, target_task_id, link_type);

CREATE TABLE device_installations (
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  id uuid NOT NULL,
  tenant_user_id uuid NOT NULL,
  installation_key_hash text NOT NULL,
  platform text,
  app_version text,
  device_model text,
  os_version text,
  push_token_encrypted text,
  status device_status NOT NULL DEFAULT 'active',
  last_seen_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY (tenant_id, id),
  UNIQUE (tenant_id, installation_key_hash),
  FOREIGN KEY (tenant_id, tenant_user_id) REFERENCES tenant_users(tenant_id, id) ON DELETE CASCADE
);
CREATE INDEX device_installations_user_status_ix ON device_installations (tenant_id, tenant_user_id, status);

CREATE TABLE task_runs (
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  id uuid NOT NULL,
  task_id uuid NOT NULL,
  workflow_version_id uuid NOT NULL,
  run_no integer NOT NULL CHECK (run_no > 0),
  state task_run_state NOT NULL DEFAULT 'draft',
  result task_result,
  performed_by_tenant_user_id uuid NOT NULL,
  device_id uuid,
  started_at timestamptz NOT NULL,
  submitted_at timestamptz,
  offline_started boolean NOT NULL DEFAULT false,
  app_version text,
  declaration_accepted_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY (tenant_id, id),
  UNIQUE (tenant_id, task_id, run_no),
  UNIQUE (tenant_id, id, task_id),
  FOREIGN KEY (tenant_id, task_id, workflow_version_id)
    REFERENCES tasks(tenant_id, id, workflow_version_id) ON DELETE RESTRICT,
  FOREIGN KEY (tenant_id, workflow_version_id) REFERENCES workflow_versions(tenant_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (tenant_id, performed_by_tenant_user_id) REFERENCES tenant_users(tenant_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (tenant_id, device_id) REFERENCES device_installations(tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT task_runs_submission_ck CHECK (
    (state IN ('submitted', 'rejected', 'approved') AND submitted_at IS NOT NULL)
    OR state = 'draft'
  )
);
CREATE INDEX task_runs_task_state_ix ON task_runs (tenant_id, task_id, state);
CREATE INDEX task_runs_worker_started_ix ON task_runs (tenant_id, performed_by_tenant_user_id, started_at DESC);

CREATE TABLE task_status_history (
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  id bigint GENERATED ALWAYS AS IDENTITY,
  task_id uuid NOT NULL,
  task_run_id uuid,
  from_status task_status NOT NULL,
  to_status task_status NOT NULL,
  reason_code text,
  reason_text text,
  changed_by_tenant_user_id uuid,
  occurred_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY (tenant_id, id),
  FOREIGN KEY (tenant_id, task_id) REFERENCES tasks(tenant_id, id) ON DELETE CASCADE,
  FOREIGN KEY (tenant_id, task_run_id, task_id)
    REFERENCES task_runs(tenant_id, id, task_id) ON DELETE RESTRICT,
  FOREIGN KEY (tenant_id, changed_by_tenant_user_id) REFERENCES tenant_users(tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT task_status_history_transition_ck CHECK (from_status <> to_status)
);
CREATE INDEX task_status_history_task_time_ix ON task_status_history (tenant_id, task_id, occurred_at);
CREATE INDEX task_status_history_time_brin ON task_status_history USING brin (occurred_at);

CREATE TABLE repeat_group_instances (
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  id uuid NOT NULL,
  task_run_id uuid NOT NULL,
  group_field_id uuid NOT NULL,
  ordinal integer NOT NULL CHECK (ordinal > 0),
  client_instance_id uuid,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY (tenant_id, id),
  UNIQUE (tenant_id, task_run_id, group_field_id, ordinal),
  FOREIGN KEY (tenant_id, task_run_id) REFERENCES task_runs(tenant_id, id) ON DELETE CASCADE,
  FOREIGN KEY (tenant_id, group_field_id) REFERENCES workflow_fields(tenant_id, id) ON DELETE RESTRICT
);
CREATE UNIQUE INDEX repeat_group_instances_client_uq
  ON repeat_group_instances (tenant_id, task_run_id, client_instance_id)
  WHERE client_instance_id IS NOT NULL;

CREATE TABLE task_answers (
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  id uuid NOT NULL,
  task_run_id uuid NOT NULL,
  field_id uuid NOT NULL,
  repeat_group_instance_id uuid,
  text_value text,
  numeric_value numeric,
  boolean_value boolean,
  date_value date,
  time_value time,
  timestamp_value timestamptz,
  json_value jsonb,
  value_unit text,
  validation_status answer_validation_status NOT NULL DEFAULT 'unvalidated',
  validation_messages jsonb NOT NULL DEFAULT '[]'::jsonb,
  captured_at timestamptz,
  captured_latitude numeric(9,6),
  captured_longitude numeric(9,6),
  captured_accuracy_m numeric CHECK (captured_accuracy_m IS NULL OR captured_accuracy_m >= 0),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY (tenant_id, id),
  FOREIGN KEY (tenant_id, task_run_id) REFERENCES task_runs(tenant_id, id) ON DELETE CASCADE,
  FOREIGN KEY (tenant_id, field_id) REFERENCES workflow_fields(tenant_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (tenant_id, repeat_group_instance_id)
    REFERENCES repeat_group_instances(tenant_id, id) ON DELETE CASCADE,
  CONSTRAINT task_answers_latitude_ck CHECK (captured_latitude IS NULL OR captured_latitude BETWEEN -90 AND 90),
  CONSTRAINT task_answers_longitude_ck CHECK (captured_longitude IS NULL OR captured_longitude BETWEEN -180 AND 180),
  CONSTRAINT task_answers_coordinates_pair_ck CHECK ((captured_latitude IS NULL) = (captured_longitude IS NULL)),
  CONSTRAINT task_answers_one_scalar_ck CHECK (
    num_nonnulls(text_value, numeric_value, boolean_value, date_value, time_value, timestamp_value, json_value) <= 1
  )
);
CREATE UNIQUE INDEX task_answers_scalar_uq
  ON task_answers (tenant_id, task_run_id, field_id) WHERE repeat_group_instance_id IS NULL;
CREATE UNIQUE INDEX task_answers_repeat_uq
  ON task_answers (tenant_id, task_run_id, repeat_group_instance_id, field_id)
  WHERE repeat_group_instance_id IS NOT NULL;
CREATE INDEX task_answers_field_validation_ix ON task_answers (tenant_id, field_id, validation_status);

CREATE TABLE answer_option_selections (
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  answer_id uuid NOT NULL,
  option_id uuid NOT NULL,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY (tenant_id, answer_id, option_id),
  FOREIGN KEY (tenant_id, answer_id) REFERENCES task_answers(tenant_id, id) ON DELETE CASCADE,
  FOREIGN KEY (tenant_id, option_id) REFERENCES workflow_field_options(tenant_id, id) ON DELETE RESTRICT
);
CREATE INDEX answer_option_selections_option_ix ON answer_option_selections (tenant_id, option_id);

CREATE TABLE answer_lookup_selections (
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  id uuid NOT NULL,
  answer_id uuid NOT NULL,
  customer_id uuid,
  site_id uuid,
  service_target_id uuid,
  part_id uuid,
  tenant_user_id uuid,
  position integer NOT NULL CHECK (position >= 0),
  display_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY (tenant_id, id),
  UNIQUE (tenant_id, answer_id, position),
  FOREIGN KEY (tenant_id, answer_id) REFERENCES task_answers(tenant_id, id) ON DELETE CASCADE,
  FOREIGN KEY (tenant_id, customer_id) REFERENCES customers(tenant_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (tenant_id, site_id) REFERENCES sites(tenant_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (tenant_id, service_target_id) REFERENCES service_targets(tenant_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (tenant_id, part_id) REFERENCES parts(tenant_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (tenant_id, tenant_user_id) REFERENCES tenant_users(tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT answer_lookup_selections_one_target_ck CHECK (
    num_nonnulls(customer_id, site_id, service_target_id, part_id, tenant_user_id) = 1
  )
);
CREATE INDEX answer_lookup_customer_ix ON answer_lookup_selections (tenant_id, customer_id);
CREATE INDEX answer_lookup_site_ix ON answer_lookup_selections (tenant_id, site_id);
CREATE INDEX answer_lookup_target_ix ON answer_lookup_selections (tenant_id, service_target_id);
CREATE INDEX answer_lookup_part_ix ON answer_lookup_selections (tenant_id, part_id);
CREATE INDEX answer_lookup_user_ix ON answer_lookup_selections (tenant_id, tenant_user_id);

CREATE TABLE task_section_results (
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  task_run_id uuid NOT NULL,
  section_id uuid NOT NULL,
  result section_result NOT NULL,
  warnings jsonb NOT NULL DEFAULT '[]'::jsonb,
  completed_at timestamptz,
  PRIMARY KEY (tenant_id, task_run_id, section_id),
  FOREIGN KEY (tenant_id, task_run_id) REFERENCES task_runs(tenant_id, id) ON DELETE CASCADE,
  FOREIGN KEY (tenant_id, section_id) REFERENCES workflow_sections(tenant_id, id) ON DELETE RESTRICT
);
CREATE INDEX task_section_results_section_result_ix ON task_section_results (tenant_id, section_id, result);

CREATE TABLE evidence_files (
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  id uuid NOT NULL,
  task_run_id uuid NOT NULL,
  answer_id uuid,
  client_upload_id uuid NOT NULL,
  evidence_type evidence_type NOT NULL,
  category text,
  object_key text NOT NULL,
  mime_type text NOT NULL,
  byte_size bigint NOT NULL CHECK (byte_size >= 0),
  sha256_hex char(64),
  capture_source capture_source NOT NULL,
  captured_at timestamptz,
  captured_latitude numeric(9,6),
  captured_longitude numeric(9,6),
  captured_accuracy_m numeric CHECK (captured_accuracy_m IS NULL OR captured_accuracy_m >= 0),
  upload_status upload_status NOT NULL DEFAULT 'pending',
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY (tenant_id, id),
  UNIQUE (tenant_id, client_upload_id),
  FOREIGN KEY (tenant_id, task_run_id) REFERENCES task_runs(tenant_id, id) ON DELETE CASCADE,
  FOREIGN KEY (tenant_id, answer_id) REFERENCES task_answers(tenant_id, id) ON DELETE CASCADE,
  CONSTRAINT evidence_files_latitude_ck CHECK (captured_latitude IS NULL OR captured_latitude BETWEEN -90 AND 90),
  CONSTRAINT evidence_files_longitude_ck CHECK (captured_longitude IS NULL OR captured_longitude BETWEEN -180 AND 180),
  CONSTRAINT evidence_files_coordinates_pair_ck CHECK ((captured_latitude IS NULL) = (captured_longitude IS NULL))
);
CREATE INDEX evidence_files_run_category_ix ON evidence_files (tenant_id, task_run_id, category);
CREATE INDEX evidence_files_answer_ix ON evidence_files (tenant_id, answer_id);
CREATE INDEX evidence_files_upload_status_ix ON evidence_files (tenant_id, upload_status, created_at);

CREATE TABLE gps_events (
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  id bigint GENERATED ALWAYS AS IDENTITY,
  task_id uuid NOT NULL,
  task_run_id uuid,
  event_type gps_event_type NOT NULL,
  latitude numeric(9,6) NOT NULL CHECK (latitude BETWEEN -90 AND 90),
  longitude numeric(9,6) NOT NULL CHECK (longitude BETWEEN -180 AND 180),
  accuracy_m numeric CHECK (accuracy_m IS NULL OR accuracy_m >= 0),
  site_distance_m numeric CHECK (site_distance_m IS NULL OR site_distance_m >= 0),
  provider text,
  is_mock_suspected boolean NOT NULL DEFAULT false,
  captured_at timestamptz NOT NULL,
  received_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY (tenant_id, id),
  FOREIGN KEY (tenant_id, task_id) REFERENCES tasks(tenant_id, id) ON DELETE CASCADE,
  FOREIGN KEY (tenant_id, task_run_id, task_id)
    REFERENCES task_runs(tenant_id, id, task_id) ON DELETE CASCADE
);
CREATE INDEX gps_events_task_time_ix ON gps_events (tenant_id, task_id, captured_at);
CREATE INDEX gps_events_run_type_ix ON gps_events (tenant_id, task_run_id, event_type);
CREATE INDEX gps_events_time_brin ON gps_events USING brin (captured_at);

CREATE TABLE parts_used (
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  id uuid NOT NULL,
  task_run_id uuid NOT NULL,
  part_id uuid,
  part_code_snapshot text,
  part_name_snapshot text,
  quantity numeric NOT NULL CHECK (quantity > 0),
  unit text,
  old_part_returned boolean,
  notes text,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY (tenant_id, id),
  FOREIGN KEY (tenant_id, task_run_id) REFERENCES task_runs(tenant_id, id) ON DELETE CASCADE,
  FOREIGN KEY (tenant_id, part_id) REFERENCES parts(tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT parts_used_identity_ck CHECK (part_id IS NOT NULL OR part_name_snapshot IS NOT NULL)
);
CREATE INDEX parts_used_run_ix ON parts_used (tenant_id, task_run_id);
CREATE INDEX parts_used_part_time_ix ON parts_used (tenant_id, part_id, created_at);

CREATE TABLE otp_challenges (
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  id uuid NOT NULL,
  task_run_id uuid NOT NULL,
  destination_hash text NOT NULL,
  code_hash text NOT NULL,
  expires_at timestamptz NOT NULL,
  attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  verified_at timestamptz,
  invalidated_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY (tenant_id, id),
  FOREIGN KEY (tenant_id, task_run_id) REFERENCES task_runs(tenant_id, id) ON DELETE CASCADE
);
CREATE INDEX otp_challenges_run_time_ix ON otp_challenges (tenant_id, task_run_id, created_at DESC);
CREATE INDEX otp_challenges_expiry_px ON otp_challenges (expires_at)
  WHERE verified_at IS NULL AND invalidated_at IS NULL;

CREATE TABLE customer_confirmations (
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  id uuid NOT NULL,
  task_run_id uuid NOT NULL,
  method confirmation_method NOT NULL,
  status confirmation_status NOT NULL,
  signer_name text,
  signer_designation text,
  signature_evidence_id uuid,
  otp_challenge_id uuid,
  exception_reason text,
  confirmed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY (tenant_id, id),
  UNIQUE (tenant_id, task_run_id),
  FOREIGN KEY (tenant_id, task_run_id) REFERENCES task_runs(tenant_id, id) ON DELETE CASCADE,
  FOREIGN KEY (tenant_id, signature_evidence_id) REFERENCES evidence_files(tenant_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (tenant_id, otp_challenge_id) REFERENCES otp_challenges(tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT customer_confirmations_method_ck CHECK (
    (method = 'signature' AND signature_evidence_id IS NOT NULL AND otp_challenge_id IS NULL)
    OR (method = 'otp' AND otp_challenge_id IS NOT NULL AND signature_evidence_id IS NULL)
    OR method = 'none'
  ),
  CONSTRAINT customer_confirmations_exception_ck CHECK (
    status NOT IN ('customer_unavailable', 'customer_refused') OR exception_reason IS NOT NULL
  )
);
CREATE INDEX customer_confirmations_status_ix ON customer_confirmations (tenant_id, status, created_at);

CREATE TABLE task_exceptions (
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  id uuid NOT NULL,
  task_id uuid NOT NULL,
  task_run_id uuid,
  field_id uuid,
  exception_type exception_type NOT NULL,
  severity exception_severity NOT NULL,
  status exception_status NOT NULL DEFAULT 'open',
  details jsonb NOT NULL DEFAULT '{}'::jsonb,
  raised_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  resolved_by_tenant_user_id uuid,
  resolved_at timestamptz,
  resolution_note text,
  PRIMARY KEY (tenant_id, id),
  FOREIGN KEY (tenant_id, task_id) REFERENCES tasks(tenant_id, id) ON DELETE CASCADE,
  FOREIGN KEY (tenant_id, task_run_id, task_id)
    REFERENCES task_runs(tenant_id, id, task_id) ON DELETE CASCADE,
  FOREIGN KEY (tenant_id, field_id) REFERENCES workflow_fields(tenant_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (tenant_id, resolved_by_tenant_user_id) REFERENCES tenant_users(tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT task_exceptions_resolution_ck CHECK (
    (status IN ('accepted', 'resolved', 'dismissed') AND resolved_at IS NOT NULL AND resolved_by_tenant_user_id IS NOT NULL)
    OR status = 'open'
  )
);
CREATE INDEX task_exceptions_queue_ix ON task_exceptions (tenant_id, status, severity, raised_at);
CREATE INDEX task_exceptions_task_ix ON task_exceptions (tenant_id, task_id, status);
CREATE INDEX task_exceptions_run_ix ON task_exceptions (tenant_id, task_run_id, status);

CREATE TABLE task_reviews (
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  id uuid NOT NULL,
  task_id uuid NOT NULL,
  task_run_id uuid NOT NULL,
  reviewer_tenant_user_id uuid NOT NULL,
  decision review_decision NOT NULL,
  reason_code text,
  comments text,
  correction_fields jsonb NOT NULL DEFAULT '[]'::jsonb,
  reviewed_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY (tenant_id, id),
  UNIQUE (tenant_id, task_run_id),
  FOREIGN KEY (tenant_id, task_id) REFERENCES tasks(tenant_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (tenant_id, task_run_id, task_id)
    REFERENCES task_runs(tenant_id, id, task_id) ON DELETE RESTRICT,
  FOREIGN KEY (tenant_id, reviewer_tenant_user_id) REFERENCES tenant_users(tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT task_reviews_rejection_reason_ck CHECK (
    decision <> 'rejected' OR reason_code IS NOT NULL OR comments IS NOT NULL
  )
);
CREATE INDEX task_reviews_reviewer_time_ix ON task_reviews (tenant_id, reviewer_tenant_user_id, reviewed_at DESC);
CREATE INDEX task_reviews_decision_time_ix ON task_reviews (tenant_id, decision, reviewed_at);

CREATE TABLE target_registration_requests (
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  id uuid NOT NULL,
  task_id uuid NOT NULL,
  site_id uuid NOT NULL,
  requested_by_tenant_user_id uuid NOT NULL,
  proposed_data jsonb NOT NULL,
  status request_status NOT NULL DEFAULT 'pending',
  reviewed_by_tenant_user_id uuid,
  created_service_target_id uuid,
  reviewed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY (tenant_id, id),
  FOREIGN KEY (tenant_id, task_id) REFERENCES tasks(tenant_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (tenant_id, site_id) REFERENCES sites(tenant_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (tenant_id, requested_by_tenant_user_id) REFERENCES tenant_users(tenant_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (tenant_id, reviewed_by_tenant_user_id) REFERENCES tenant_users(tenant_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (tenant_id, created_service_target_id) REFERENCES service_targets(tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT target_registration_review_ck CHECK (
    (status IN ('approved', 'rejected') AND reviewed_by_tenant_user_id IS NOT NULL AND reviewed_at IS NOT NULL)
    OR status = 'pending'
  )
);
CREATE INDEX target_registration_queue_ix ON target_registration_requests (tenant_id, status, created_at);
CREATE INDEX target_registration_site_ix ON target_registration_requests (tenant_id, site_id, status);

CREATE TABLE sync_mutations (
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  mutation_id uuid NOT NULL,
  device_id uuid NOT NULL,
  task_id uuid,
  entity_type text NOT NULL,
  entity_id uuid NOT NULL,
  operation text NOT NULL,
  payload_hash char(64) NOT NULL,
  client_occurred_at timestamptz NOT NULL,
  received_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  status sync_mutation_status NOT NULL DEFAULT 'received',
  error_code text,
  PRIMARY KEY (tenant_id, mutation_id),
  FOREIGN KEY (tenant_id, device_id) REFERENCES device_installations(tenant_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (tenant_id, task_id) REFERENCES tasks(tenant_id, id) ON DELETE CASCADE
);
CREATE INDEX sync_mutations_device_time_ix ON sync_mutations (tenant_id, device_id, received_at DESC);
CREATE INDEX sync_mutations_task_status_ix ON sync_mutations (tenant_id, task_id, status);
CREATE INDEX sync_mutations_time_brin ON sync_mutations USING brin (received_at);

CREATE TABLE import_jobs (
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  id uuid NOT NULL,
  import_type import_type NOT NULL,
  file_object_key text NOT NULL,
  status import_status NOT NULL DEFAULT 'uploaded',
  total_rows integer CHECK (total_rows IS NULL OR total_rows >= 0),
  valid_rows integer CHECK (valid_rows IS NULL OR valid_rows >= 0),
  rejected_rows integer CHECK (rejected_rows IS NULL OR rejected_rows >= 0),
  created_by_tenant_user_id uuid NOT NULL,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  completed_at timestamptz,
  PRIMARY KEY (tenant_id, id),
  FOREIGN KEY (tenant_id, created_by_tenant_user_id) REFERENCES tenant_users(tenant_id, id) ON DELETE RESTRICT
);
CREATE INDEX import_jobs_type_time_ix ON import_jobs (tenant_id, import_type, created_at DESC);
CREATE INDEX import_jobs_status_time_ix ON import_jobs (tenant_id, status, created_at);

CREATE TABLE import_rows (
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  import_job_id uuid NOT NULL,
  row_no integer NOT NULL CHECK (row_no > 0),
  raw_data jsonb,
  normalized_data jsonb,
  status import_row_status NOT NULL,
  errors jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_record_type text,
  created_record_id uuid,
  PRIMARY KEY (tenant_id, import_job_id, row_no),
  FOREIGN KEY (tenant_id, import_job_id) REFERENCES import_jobs(tenant_id, id) ON DELETE CASCADE
);
CREATE INDEX import_rows_status_ix ON import_rows (tenant_id, import_job_id, status);

CREATE TABLE notifications (
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  id uuid NOT NULL,
  recipient_tenant_user_id uuid NOT NULL,
  task_id uuid,
  notification_type text NOT NULL,
  title text NOT NULL,
  body text,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  status notification_status NOT NULL DEFAULT 'unread',
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  read_at timestamptz,
  PRIMARY KEY (tenant_id, id),
  FOREIGN KEY (tenant_id, recipient_tenant_user_id) REFERENCES tenant_users(tenant_id, id) ON DELETE CASCADE,
  FOREIGN KEY (tenant_id, task_id) REFERENCES tasks(tenant_id, id) ON DELETE CASCADE
);
CREATE INDEX notifications_recipient_queue_ix
  ON notifications (tenant_id, recipient_tenant_user_id, status, created_at DESC);
CREATE INDEX notifications_task_time_ix ON notifications (tenant_id, task_id, created_at);

CREATE TABLE generated_reports (
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  id uuid NOT NULL,
  task_id uuid NOT NULL,
  task_run_id uuid NOT NULL,
  report_type text NOT NULL,
  template_version integer NOT NULL CHECK (template_version > 0),
  object_key text NOT NULL,
  sha256_hex char(64),
  generated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  generated_by_tenant_user_id uuid,
  PRIMARY KEY (tenant_id, id),
  UNIQUE (tenant_id, task_run_id, report_type, template_version),
  FOREIGN KEY (tenant_id, task_id) REFERENCES tasks(tenant_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (tenant_id, task_run_id, task_id)
    REFERENCES task_runs(tenant_id, id, task_id) ON DELETE RESTRICT,
  FOREIGN KEY (tenant_id, generated_by_tenant_user_id) REFERENCES tenant_users(tenant_id, id) ON DELETE RESTRICT
);
CREATE INDEX generated_reports_task_time_ix ON generated_reports (tenant_id, task_id, generated_at DESC);

CREATE TABLE audit_logs (
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  id bigint GENERATED ALWAYS AS IDENTITY,
  actor_tenant_user_id uuid,
  actor_platform_user_id uuid,
  action text NOT NULL,
  entity_type text NOT NULL,
  entity_id uuid NOT NULL,
  task_id uuid,
  before_data jsonb,
  after_data jsonb,
  request_id uuid,
  ip_hash text,
  occurred_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY (tenant_id, id),
  FOREIGN KEY (tenant_id, actor_tenant_user_id) REFERENCES tenant_users(tenant_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (actor_platform_user_id) REFERENCES users(id) ON DELETE RESTRICT,
  FOREIGN KEY (tenant_id, task_id) REFERENCES tasks(tenant_id, id) ON DELETE CASCADE,
  CONSTRAINT audit_logs_actor_ck CHECK (num_nonnulls(actor_tenant_user_id, actor_platform_user_id) <= 1)
);
CREATE INDEX audit_logs_entity_time_ix ON audit_logs (tenant_id, entity_type, entity_id, occurred_at DESC);
CREATE INDEX audit_logs_actor_time_ix ON audit_logs (tenant_id, actor_tenant_user_id, occurred_at DESC);
CREATE INDEX audit_logs_task_time_ix ON audit_logs (tenant_id, task_id, occurred_at DESC);
CREATE INDEX audit_logs_time_brin ON audit_logs USING brin (occurred_at);

-- Updated-at triggers for mutable records.
DO $$
DECLARE
  table_name text;
BEGIN
  FOREACH table_name IN ARRAY ARRAY[
    'users', 'tenants', 'tenant_settings', 'branches', 'tenant_users', 'teams',
    'customers', 'sites', 'service_targets', 'parts', 'workflows',
    'recurrence_plans', 'tasks', 'device_installations', 'task_answers'
  ]
  LOOP
    EXECUTE format(
      'CREATE TRIGGER %I_set_updated_at BEFORE UPDATE ON field_ops.%I '
      'FOR EACH ROW EXECUTE FUNCTION field_ops.set_updated_at()',
      table_name,
      table_name
    );
  END LOOP;
END;
$$;

-- Tenant row-level security. Application transactions must set app.tenant_id.
DO $$
DECLARE
  table_name text;
BEGIN
  FOREACH table_name IN ARRAY ARRAY[
    'tenant_settings', 'branches', 'tenant_users', 'teams', 'team_members',
    'customers', 'sites', 'service_targets', 'parts', 'workflows',
    'workflow_versions', 'workflow_sections', 'workflow_fields',
    'workflow_field_options', 'workflow_rules', 'workflow_rule_conditions',
    'workflow_rule_actions', 'recurrence_plans', 'tasks', 'task_assignments',
    'task_links', 'device_installations', 'task_runs', 'task_status_history',
    'repeat_group_instances', 'task_answers', 'answer_option_selections',
    'answer_lookup_selections', 'task_section_results', 'evidence_files',
    'gps_events', 'parts_used', 'otp_challenges', 'customer_confirmations',
    'task_exceptions', 'task_reviews', 'target_registration_requests',
    'sync_mutations', 'import_jobs', 'import_rows', 'notifications',
    'generated_reports', 'audit_logs'
  ]
  LOOP
    EXECUTE format('ALTER TABLE field_ops.%I ENABLE ROW LEVEL SECURITY', table_name);
    EXECUTE format('ALTER TABLE field_ops.%I FORCE ROW LEVEL SECURITY', table_name);
    EXECUTE format(
      'CREATE POLICY tenant_isolation ON field_ops.%I '
      'USING (tenant_id = nullif(current_setting(''app.tenant_id'', true), '''')::uuid) '
      'WITH CHECK (tenant_id = nullif(current_setting(''app.tenant_id'', true), '''')::uuid)',
      table_name
    );
  END LOOP;
END;
$$;

COMMENT ON TABLE workflow_versions IS 'Published workflow versions are immutable; enforce immutable updates in the service or with a dedicated trigger.';
COMMENT ON TABLE task_runs IS 'Each submission/re-submission is an immutable run; rejection creates a new run.';
COMMENT ON TABLE sync_mutations IS 'Client-supplied mutation_id provides exactly-once/idempotent offline mutation handling.';
COMMENT ON TABLE audit_logs IS 'Append-only audit trail. Restrict UPDATE and DELETE privileges from application roles.';

COMMIT;

-- High-volume deployment notes (apply after workload testing, not blindly):
-- 1. Monthly range partition task_status_history, gps_events, sync_mutations and audit_logs.
-- 2. Consider time/tenant partitioning for tasks only when table size and access patterns justify it.
-- 3. Add PostGIS geography(Point,4326) columns and GiST indexes when radius/nearest-site queries are frequent.
-- 4. Put evidence bytes in object storage; evidence_files stores immutable metadata and hashes only.
-- 5. Use read replicas/materialized aggregates for dashboards; do not overload OLTP indexes for analytics.
-- 6. Deny UPDATE/DELETE on published workflow_versions, submitted task_runs, evidence metadata and audit_logs.
